config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entities, only: [:new, :create] 
  resources :groups, only: [:index, :show, :new, :create] 
  resources :users

  root "application#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :create, Group
    can :create, Entity
    can :create, Expense
    can :read, Entity, author_id: user.id
    can :read, Group, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :expenses
  has_many :groups, through: :expenses

  validates :name, presence: true
  validates :amount, presence: true
  validates :author_id, presence: true

  accepts_nested_attributes_for :expenses
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :expenses
  has_many :entities, through: :expenses

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    entities = self.entities
    total = 0
    entities.each do |entity|
      total += entity.amount
    end
    total
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def index; end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /entities/new
  def new
    @entity = Entity.new
    @groups = Group.where(user: current_user)
    @expense = @entity.expenses.build
  end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to group_path(@entity.expenses[0].group_id), notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :author_id, :amount, expenses_attributes: [:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    set_group
    @entities = @group.entities.order('created_at DESC')
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/views/application/index.html.erb
<% if !user_signed_in? %>
<div class="splash-screen">
<h1>SaveIT</h1>
</div>
<div class="registration-links">
  <%= link_to "LOG IN", new_user_session_path, class: "btn" %>
  <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-secondary" %>
</div>
<% else %>
<script type="text/javascript">
  window.location.href="/groups"  
</script>
<% end %>

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= entity.author_id %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= entity.amount %>
  </p>

</div>

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "Name" %>
  </div>

  <div>
    <%= form.hidden_field :author_id, value: current_user.id %>
  </div>

  <div>
    <%= form.number_field :amount, placeholder: "Amount" %>
  </div>

  <%= form.fields_for :expenses do |expense_subform| %>
    <%= expense_subform.collection_select :group_id, @groups.order(:name),:id,:name, include_blank: "--Choose Category--" %>
    <% end %>
  <div>
    <%= form.submit "Create Expense", class: "create-expense" %>
  </div>
<% end %>

app/views/entities/new.html.erb
<section class="new-expense-section">
<header class="header">
<%= link_to "BACK", group_path(params[:current_group]) %>
  <h2>New Expense</h2>
  <div></div>
</header>

<%= render "form", entity: @entity %>

</section> 

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "Name" %>
  </div>

  <div class="select-icon-field">
    <%= form.text_field :icon, class: 'icon-input', placeholder: "Click on Select an Icon" %>
    <span class="select-icon">Select an Icon</span>
  </div>

  <div>
  <%= form.hidden_field :user_id, value: current_user.id  %>
  </div>
 
  <div>
    <%= form.submit "Create Group", class: "create-group" %>
  </div>
<% end %>


<div class="icon-picker-container hidden"> 

  <div class="icon-picker">
  <span class="close-icon-picker-btn"><i class="fa-solid fa-xmark fa-2x"></i></span>
  <h1>Pick an Icon</h1>
 
  <ul class="icons-list">
    <li class="icon"><i class="fa-solid fa-utensils fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-cart-shopping fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-house fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-phone fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-paw fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-laptop fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-car fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-plane fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-file-invoice-dollar fa-2x"></i></li>
    <li class="icon"><i class="fa-solid fa-shirt fa-2x"></i></li>

  </ul>

  </div>
  
</div>

app/views/groups/index.html.erb
<section class="groups-section">

<header class="header">
<%= button_to "Sign out", destroy_user_session_path, method: :delete, data: {turbo: false},  class: "log-out-button" %>
    
  <h2>Categories</h2>
  <div></div>
</header>

<p style="color: green"><%= notice %></p>




  <ul class="groups-lis">
  <% @groups.each do |group| %>
    <% if can? :read, group %>
    <li class="group-item">
      <span><i class="<%= group.icon %> fa-3x"></i></span>
      <p> <%= group.name %> </p>
      <p> $<%= group.total_amount %></p>
      <p>
        <%= link_to "Show", group_path(group.id), class: "show-button" %>
      </p>
    </li>
    <% end %>
  <% end %>
  </ul>

<%= link_to "New Category", new_group_path, class: "new-group" %>

</section>

app/views/groups/new.html.erb
<section class="create-category-section">
  <header class="header">
    <%= link_to "BACK", root_path %>
    <h2>New Category</h2>
    <div></div>
  </header>

  <%= render "form", group: @group %>

</section>

app/views/groups/show.html.erb
<section class="expenses-section">

<header class="header">
<%= link_to "BACK", groups_path %>
  <h2><%= @group.name %></h2>
  <span class="total-amount-header"> $<%= @group.total_amount %></span>
</header>

<p style="color: green"><%= notice %></p>


<div>
  <ul class="transactions-list">
    <% @entities.each do  |entity| %>
      <li class="transaction-item">
        <span> <%= entity.name %> </span>
        <span> <%= entity.amount %> $ </span>
        <span> <%= entity.created_at.strftime("%d %b %y") %> </span>
      </li>
    <% end %>
  </ul>
</div>

<%= button_to "Add Transaction", new_entity_path, method: :get, class: "new-entity", params: {current_group: @group.id} %>


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/9b54de88d2.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>